### ISSUE TITLE
TypeError: Cannot read property 'trimRight' of undefined

### ISSUE THREAD

**Issue by TakiTamSlu** [khrome/ascii-art#20]
From version ascii-art@2.1.2 does not work.
My script:
```
ascii.font(args.join("    "), "Doom", function(rendered) {
            rendered = rendered.trimRight();
                
            message.channel.send(rendered, {
                code: "md"
            });
});
```
```
TypeError: Cannot read property 'trimRight' of undefined
    at /test/commands/ascii.js:20:33
    at /test/node_modules/ascii-art-font/font.js:146:17
    at /test/node_modules/ascii-art-font/font.js:90:17
    at /test/node_modules/ascii-art-font/font.js:37:21
    at Object._parseFont (test/node_modules/ascii-art-font/font.js:53:13)
    at /testa/node_modules/ascii-art-font/font.js:35:33
    at /test/node_modules/ascii-art-font/font.js:74:26
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
```

**Comment by khrome** [comment]
I did a poor job of advertising this update, but the callback now uses standard error handling.. try:
```js
ascii.font(args.join("    "), "Doom", function(err, rendered) {
            rendered = rendered.trimRight();
                
            message.channel.send(rendered, {
                code: "md"
            });
});
```
